### ISSUE TITLE
Exception No module named '_cffi_backend'

### ISSUE THREAD

**Issue by oliviercarizzoni** [Garulf/Github-Quick-Launcher#15]
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/12/2022 23:35:35
Exception:
Github Quick Launcher Exception: 
Websites: https://github.com/Garulf/github-quick-launcher
Author: Garulf
Version: 1.5.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Github Quick Launcher|Traceback (most recent call last):
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\run.py", line 9, in <module>
    from plugin.main import GithubQuickLauncher
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\plugin\main.py", line 7, in <module>
    from github import Github, NamedUser, Repository
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\MainClass.py", line 59, in <module>
    import github.Event
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\Organization.py", line 50, in <module>
    import github.Repository
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\Repository.py", line 125, in <module>
    import github.PublicKey
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\nacl\public.py", line 16, in <module>
    import nacl.bindings
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\nacl\bindings\__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\nacl\bindings\crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

 ---> System.IO.InvalidDataException: Github Quick Launcher|Traceback (most recent call last):
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\run.py", line 9, in <module>
    from plugin.main import GithubQuickLauncher
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\plugin\main.py", line 7, in <module>
    from github import Github, NamedUser, Repository
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\MainClass.py", line 59, in <module>
    import github.Event
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\Organization.py", line 50, in <module>
    import github.Repository
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\Repository.py", line 125, in <module>
    import github.PublicKey
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\nacl\public.py", line 16, in <module>
    import nacl.bindings
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\nacl\bindings\__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "C:\Users\olivier\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.5.0\lib\nacl\bindings\crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: [No module named '_cffi_backend'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 616
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 590
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by oliviercarizzoni** [comment]
[2022-10-12.txt](https://github.com/Garulf/Github-Quick-Launcher/files/9768935/2022-10-12.txt)

**Comment by Garulf** [comment]
Using Python 3.8 should fix this issue.
