### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by kubalav** [Garulf/Github-Quick-Launcher#18]
This exception throws after enter activation keyword…

Log:

<details>
<summary>Details</summary>

Flow Launcher version: 1.16.2
OS Version: 20348.1787
IntPtr Length: 8
x64: True

Python Path: C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 10/14/2023 04:58:58
Exception:
Github Quick Launcher Exception: 
Websites: https://github.com/Garulf/github-quick-launcher
Author: Garulf
Version: 1.6.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\run.py", line 9, in <module>
    from plugin.main import GithubQuickLauncher
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\plugin\main.py", line 7, in <module>
    from github import Github, NamedUser, Repository
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\MainClass.py", line 59, in <module>
    import github.Event
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\Organization.py", line 50, in <module>
    import github.Repository
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\Repository.py", line 125, in <module>
    import github.PublicKey
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\nacl\public.py", line 16, in <module>
    import nacl.bindings
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\nacl\bindings\__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\nacl\bindings\crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\run.py", line 9, in <module>
    from plugin.main import GithubQuickLauncher
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\plugin\main.py", line 7, in <module>
    from github import Github, NamedUser, Repository
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\MainClass.py", line 59, in <module>
    import github.Event
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\Organization.py", line 50, in <module>
    import github.Repository
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\Repository.py", line 125, in <module>
    import github.PublicKey
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\nacl\public.py", line 16, in <module>
    import nacl.bindings
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\nacl\bindings\__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "C:\Users\Administrator\Downloads\FlowLauncher\app-1.16.2\UserData\Plugins\Github Quick Launcher-1.6.0\lib\nacl\bindings\crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

</details>

**Comment by Garulf** [comment]
Sadly it looks like the library I was using is not pure Python. 

This issue is caused by using Python 3.11 on a plugin was built using 3.8.

**Comment by Garulf** [comment]
Just a quick update, i am currently in the process of upgrading all my plugins and will get to this when I can.

**Comment by blankster** [comment]
Thanks in advance @Garulf 👍👍👍

**Comment by Garulf** [comment]
I released a package version that should work with Flow Launchers new default Python version default.
