### ISSUE TITLE
Error in Github Quick Launcher

### ISSUE THREAD

**Issue by debug-cli** [Garulf/Github-Quick-Launcher#19]
I will upload the log file, but here is the exception:

Flow Launcher version: 1.16.2
OS Version: 23601.1000
IntPtr Length: 8
x64: True

Python Path: C:\Users\User\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 12/12/2023 17:00:16
Exception:
Github Quick Launcher Exception: 
Websites: https://github.com/Garulf/github-quick-launcher
Author: Garulf
Version: 1.6.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\run.py", line 9, in <module>
    from plugin.main import GithubQuickLauncher
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\plugin\main.py", line 7, in <module>
    from github import Github, NamedUser, Repository
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\MainClass.py", line 59, in <module>
    import github.Event
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\Organization.py", line 50, in <module>
    import github.Repository
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\Repository.py", line 125, in <module>
    import github.PublicKey
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\nacl\public.py", line 16, in <module>
    import nacl.bindings
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\nacl\bindings\__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\nacl\bindings\crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\run.py", line 9, in <module>
    from plugin.main import GithubQuickLauncher
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\plugin\main.py", line 7, in <module>
    from github import Github, NamedUser, Repository
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\MainClass.py", line 59, in <module>
    import github.Event
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\Event.py", line 32, in <module>
    import github.NamedUser
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\NamedUser.py", line 44, in <module>
    import github.Organization
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\Organization.py", line 50, in <module>
    import github.Repository
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\Repository.py", line 125, in <module>
    import github.PublicKey
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\github\PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\nacl\public.py", line 16, in <module>
    import nacl.bindings
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\nacl\bindings\__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-1.6.0\lib\nacl\bindings\crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

log file from 12/12/2023

[2023-12-12.txt](https://github.com/Garulf/Github-Quick-Launcher/files/13654667/2023-12-12.txt)

**Comment by Garulf** [comment]
Its related to: https://github.com/Garulf/Github-Quick-Launcher/issues/18

The 3rd party GitHub library i am using has compiled code in it making using different versions of Python impossible.

**Comment by Garulf** [comment]
I released a package version that should work with Flow Launchers new default Python version default.

**Comment by BloxyYT** [comment]
> I released a package version that should work with Flow Launchers new default Python version default.

Is 3.8 the default?

**Comment by Garulf** [comment]
> > I released a package version that should work with Flow Launchers new default Python version default.
> 
> Is 3.8 the default?

Python 3.8 was the default, we've upgraded to Python 3.11 now.

**Comment by BloxyYT** [comment]
> Python 3.8 was the default, we've upgraded to Python 3.11 now.
Switching right now
