### ISSUE TITLE
There is an issue for Flow launcher

### ISSUE THREAD

**Issue by neondev27** [Garulf/Github-Quick-Launcher#22]
[2024-01-20.txt](https://github.com/Garulf/Github-Quick-Launcher/files/13996809/2024-01-20.txt)

Flow Launcher version: 1.16.2
OS Version: 26016.1012
IntPtr Length: 8
x64: True

Python Path: C:\Python310\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 01/20/2024 08:23:23
Exception:
Github Quick Launcher Exception: 
Websites: https://github.com/Garulf/github-quick-launcher
Author: Garulf
Version: 3.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\__main__.py", line 1, in <module>
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\plugin.py", line 3, in <module>
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\__init__.py", line 5, in <module>
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\plugin.py", line 12, in <module>
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\jsonrpc.py", line 8, in <module>
ModuleNotFoundError: No module named 'typing_extensions'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\__main__.py", line 1, in <module>
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\plugin.py", line 3, in <module>
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\__init__.py", line 5, in <module>
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\plugin.py", line 12, in <module>
  File "C:\Users\D6\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-3.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\jsonrpc.py", line 8, in <module>
ModuleNotFoundError: No module named 'typing_extensions'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I got that error...

**Comment by Garulf** [comment]
Looks like `typing-extension` a compatibility package for older Python versions was missing.

Should be fixed by: https://github.com/Garulf/Github-Quick-Launcher/pull/23

**Comment by Garulf** [comment]
Fix released: https://github.com/Garulf/Github-Quick-Launcher/releases/tag/v3.0.1

It may take a moment to show up in the Flow Launcher plugin store.

If you'd like you can manually install by typing the following into Flow Launcher:
`pm install https://github.com/Garulf/Github-Quick-Launcher/releases/download/v3.0.1/Github-Quick-Launcher-3.0.1.zip`
