### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by FrostyNick** [Garulf/Github-Quick-Launcher#25]
"GitHub Quick Launcher: Failed to respond"

Flow Launcher version: 1.17.1
OS Version: 22621.3007
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Python312\pythonw.exe
Node Path: 
Date: 02/08/2024 20:48:12
Exception:
Github Quick Launcher Exception: 
Websites: https://github.com/Garulf/github-quick-launcher
Author: Garulf
Version: 3.2.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\__main__.py", line 1, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\plugin.py", line 4, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\__init__.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\backends\__init__.py", line 6, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\_utils.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\__init__.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\connectionpool.py", line 11, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\exceptions.py", line 2, in <module>
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\__main__.py", line 1, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\plugin.py", line 4, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\__init__.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\backends\__init__.py", line 6, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\_utils.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\__init__.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\connectionpool.py", line 11, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\exceptions.py", line 2, in <module>
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

# Update

I forgot to add node path to launcher. Still, plugin isn't working:

Flow Launcher version: 1.17.1
OS Version: 22621.3007
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Python312\pythonw.exe
Node Path: C:\Users\fight\scoop\apps\nodejs\current\node.exe
Date: 02/08/2024 21:12:57
Exception:
Github Quick Launcher Exception: 
Websites: https://github.com/Garulf/github-quick-launcher
Author: Garulf
Version: 3.2.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\__main__.py", line 1, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\plugin.py", line 4, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\__init__.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\backends\__init__.py", line 6, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\_utils.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\__init__.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\connectionpool.py", line 11, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\exceptions.py", line 2, in <module>
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\__main__.py", line 1, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\plugin.py", line 4, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\__init__.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\backends\__init__.py", line 6, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\requests_cache\_utils.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\__init__.py", line 7, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\connectionpool.py", line 11, in <module>
  File "C:\Users\fight\scoop\apps\flow-launcher\current\app-1.17.1\UserData\Plugins\Github Quick Launcher-3.2.0\Github-Quick-Launcher.pyz\urllib3\exceptions.py", line 2, in <module>
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Sorry looks like an issue with Python 3.12 and a library dependency. 

Please downgrade Python to 3.11

**Comment by FrostyNick** [comment]
Can confirm setting path to Python 3.11.6 *and* a computer restart did the trick. Thank you
