### ISSUE TITLE
Github Quick Launcher: Failed to respond!

### ISSUE THREAD

**Issue by AdnanNezovic** [Garulf/Github-Quick-Launcher#30]
[2024-02-29.txt](https://github.com/Garulf/Github-Quick-Launcher/files/14454133/2024-02-29.txt)

Flow Launcher version: 1.17.2
OS Version: 22631.3155
IntPtr Length: 8
x64: True

Python Path: C:\Users\Adnan\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 02/29/2024 23:19:21
Exception:
Github Quick Launcher Exception: 
Websites: https://github.com/Garulf/github-quick-launcher
Author: Garulf
Version: 4.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\__main__.py", line 8, in <module>
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\plugin.py", line 14, in main
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\plugin.py", line 74, in run
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\event.py", line 34, in __call__
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\event.py", line 29, in __call__
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\query.py", line 34, in query
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\github\MainClass.py", line 465, in search_repositories
AssertionError: need at least one qualifier

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\__main__.py", line 8, in <module>
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\plugin.py", line 14, in main
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\plugin.py", line 74, in run
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\event.py", line 34, in __call__
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\pyflowlauncher\event.py", line 29, in __call__
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\query.py", line 34, in query
  File "C:\Users\Adnan\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\github\MainClass.py", line 465, in search_repositories
AssertionError: need at least one qualifier

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jonesy-b-dev** [comment]
Same over here
```
Flow Launcher version: 1.17.2
OS Version: 23585.1001
IntPtr Length: 8
x64: True

Python Path: C:\Users\jonas\.pyenv\pyenv-win\versions\3.12.1\python.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 04/04/2024 11:07:26
Exception:
Github Quick Launcher Exception: 
Websites: https://github.com/Garulf/github-quick-launcher
Author: Garulf
Version: 4.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\__main__.py", line 1, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\requests_cache\__init__.py", line 7, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\requests_cache\backends\__init__.py", line 6, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\requests_cache\_utils.py", line 7, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\urllib3\__init__.py", line 7, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\urllib3\connectionpool.py", line 11, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\urllib3\exceptions.py", line 2, in <module>
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\__main__.py", line 1, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\requests_cache\__init__.py", line 7, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\requests_cache\backends\__init__.py", line 6, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\requests_cache\_utils.py", line 7, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\urllib3\__init__.py", line 7, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\urllib3\connectionpool.py", line 11, in <module>
  File "C:\Users\jonas\AppData\Roaming\FlowLauncher\Plugins\Github Quick Launcher-4.0.0\Github-Quick-Launcher.pyz\urllib3\exceptions.py", line 2, in <module>
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Garulf** [comment]
@jonesy-b-dev this is a separate issue. 

This plugin unfortunately only supports Python 3.8-3.11 due to a library dependency not being available for 3.12. 

To fix your issue either downgrade your Python version or manual install the plugins 5.0 beta that should work here:

https://github.com/Garulf/Github-Quick-Launcher/releases/tag/v5.0.0-dev.3

**Comment by Garulf** [comment]
@AdnanNezovic This should be somewhat fixed in later versions.

**Comment by jonesy-b-dev** [comment]
Ah okay thanks
